apiVersion: v2
kind: Pod
metadata:
  name: my-web
  labels:
    env: prod
    app: main
    tier: frontend
    owner: SergeiChes
spec:
  containers:
  - name: container-apache
    image: nginx:latest
    ports:
    - containerPort: 80
