apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
  labels:
    app: my-k8s2-deployment
spec:
  replicas: 3
  selector:
    matchlabels:
      project: kgb2
  template:
    metadata:
      labels:
        progect: kgb2 # Service will look forward
    spec:
      containers:
      - name: kgb2_web
        image: adv4000/k8sphp:version2
        ports:
        - containerport: 80
