apiVersion: v1
kind: Service
metadata:
  name: my-single-pod2-service
  labels:
    env: prod
    owner: SergeiChes
spec:
  selector:
    project: kgb2 #Selectiing PODS with those lLabels!!!
  type: LoadBalancer
  ports:
  - name: app2-listener
    protocol: TCP
    port: 80 # Port on Load Balancer
    targetPort: 80 # Port on POD

