apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sergei-super-cluster
  region: us-east-1

#vpc:
#  subnets:
#    private:
#      us-east-1a: { id: subnet-ffffffffffff  }
#      us-east-1a: { id: subnet-ffffffffffff  }
#      us-east-1a: { id: subnet-ffffffffffff  }

nodeGroups:
  - name: worker-nodes-group-1
    instanceType: m5.large
    desiredCapacity: 2
  - name: worker-nodes-group-2
    instanceType: r5.large
    desiredCapacity: 2

